### ISSUE TITLE
NullPointerException whil running org.avenir.reinforce.AuerDeterministic

### ISSUE THREAD

**Issue by Riaz123** [pranab/avenir#1]

**Comment by Riaz123** [comment]
I'm trying to run Multi-Arm Bandit (org.avenir.reinforce.AuerDeterministic). I have generated data using python scripts : "./price_opt.py price 100 price_stat.txt > inc_return1.txt" and ./price_opt.py inret price_stat.txt 2 > agr_ret.txt. 
I placed  agr_ret.txt, inc_return1.txt and price_stat.txt in the input path of multi arm bandit MR (file:///home/administrator/MAB/avenir/resource/input).

Please find the below avenir_hadoop.xml , which I have used to build uber jar.
I used ant command to build the uber jar (ant -f avenir_hadoop.xml)

<project name="avenir_for_hadoop" default="uber-jar" basedir=".">
<target name="uber-jar">
    <echo>Packaging into a single uber JAR</echo>
	<jar destfile="uber-avenir-1.0.jar">
		<zipgroupfileset dir="/home/administrator/MAB/avenir/target" includes="avenir-1.0.jar" /> 
		<zipgroupfileset dir="/home/administrator/MAB/chombo/target" includes="chombo-1.0.jar" />
                <zipgroupfileset dir="/home/administrator/MAB/hoidla/target" includes="hoidla-1.0.jar" /> 
		<zipgroupfileset dir="/home/administrator/MAB/lib" includes="aws-java-sdk-1.3.22.jar,jackson-core-lgpl-1.6.3.jar,jackson-mapper-lgpl-1.6.3.jar,lucene-core-3.5.0.jar" /> 
	</jar>
</target>
</project>

 I made a local folder has HDFS file for input and output. I set JAR_NAME to the path of uber jar which has both avenir jar, chombo jar , holida jar and other jars as per your documentation.  (JAR_NAME=/home/administrator/MAB/avenir/resource/uber-avenir-1.0.jar) and CLASS_NAME=org.avenir.reinforce.AuerDeterministic (since I'm running for UCB algo). 

When I run "hadoop jar $JAR_NAME  $CLASS_NAME -Dconf.path=/home/administrator/MAB/bin/avenir/prop.properties $IN_PATH $OUT_PATH". 

I get the below error 


java.lang.Exception: java.lang.NullPointerException
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:491)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:551)
Caused by: java.lang.NullPointerException
	at org.avenir.reinforce.AuerDeterministic$BanditMapper.collectItemsByValue(AuerDeterministic.java:265)
	at org.avenir.reinforce.AuerDeterministic$BanditMapper.deterministicAuerSelect(AuerDeterministic.java:210)
	at org.avenir.reinforce.AuerDeterministic$BanditMapper.select(AuerDeterministic.java:189)
	at org.avenir.reinforce.AuerDeterministic$BanditMapper.cleanup(AuerDeterministic.java:136)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:149)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:793)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/11/23 04:56:14 INFO mapreduce.Job: Job job_local505455889_0001 running in uber mode : false
17/11/23 04:56:14 INFO mapreduce.Job:  map 100% reduce 0%
17/11/23 04:56:14 INFO mapreduce.Job: Job job_local505455889_0001 failed with state FAILED due to: NA
17/11/23 04:56:14 INFO mapreduce.Job: Counters: 22
	File System Counters
		FILE: Number of bytes read=11059374
		FILE: Number of bytes written=11601280
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=0
		HDFS: Number of bytes written=0
		HDFS: Number of read operations=0
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=0
	Map-Reduce Framework
		Map input records=793
		Map output records=99
		Map output bytes=1089
		Map output materialized bytes=1293
		Input split bytes=127
		Combine input records=0
		Spilled Records=99
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=0
		Total committed heap usage (bytes)=371720192
	File Input Format Counters 
		Bytes Read=18244

**Comment by pranab** [comment]
Please send me the properties file

Sent from my iPhone

Pranab
http://www.linkedin.com/in/pkghosh
http://pkghosh.wordpress.com


On Nov 23, 2017, at 5:11 PM, Riaz123 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying to run Multi-Arm Bandit (org.avenir.reinforce.AuerDeterministic). I have generated data using python scripts : "./price_opt.py price 100 price_stat.txt > inc_return1.txt" and ./price_opt.py inret price_stat.txt 2 > agr_ret.txt.

Placed agr_ret.txt, inc_return1.txt and price_stat.txt in the input path of multi arm bandit MR (file:///home/administrator/MAB/avenir/resource/input). I made a local folder has HDFS file for input and output. I set JAR_NAME to the path of uber jar which has both avenir jar, chombo jar , holida jar and other jars as per your documentation. (JAR_NAME=/home/administrator/MAB/avenir/resource/uber-avenir-1.0.jar) and CLASS_NAME=org.avenir.reinforce.AuerDeterministic (since I'm running for UCB algo).

When I run "hadoop jar $JAR_NAME $CLASS_NAME -Dconf.path=/home/administrator/MAB/bin/avenir/prop.properties $IN_PATH $OUT_PATH".

I get the below error

java.lang.Exception: java.lang.NullPointerException
at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:491)
at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:551)
Caused by: java.lang.NullPointerException
at org.avenir.reinforce.AuerDeterministic$BanditMapper.collectItemsByValue(AuerDeterministic.java:265)
at org.avenir.reinforce.AuerDeterministic$BanditMapper.deterministicAuerSelect(AuerDeterministic.java:210)
at org.avenir.reinforce.AuerDeterministic$BanditMapper.select(AuerDeterministic.java:189)
at org.avenir.reinforce.AuerDeterministic$BanditMapper.cleanup(AuerDeterministic.java:136)
at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:149)
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:793)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:270)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
17/11/23 04:56:14 INFO mapreduce.Job: Job job_local505455889_0001 running in uber mode : false
17/11/23 04:56:14 INFO mapreduce.Job: map 100% reduce 0%
17/11/23 04:56:14 INFO mapreduce.Job: Job job_local505455889_0001 failed with state FAILED due to: NA
17/11/23 04:56:14 INFO mapreduce.Job: Counters: 22
File System Counters
FILE: Number of bytes read=11059374
FILE: Number of bytes written=11601280
FILE: Number of read operations=0
FILE: Number of large read operations=0
FILE: Number of write operations=0
HDFS: Number of bytes read=0
HDFS: Number of bytes written=0
HDFS: Number of read operations=0
HDFS: Number of large read operations=0
HDFS: Number of write operations=0
Map-Reduce Framework
Map input records=793
Map output records=99
Map output bytes=1089
Map output materialized bytes=1293
Input split bytes=127
Combine input records=0
Spilled Records=99
Failed Shuffles=0
Merged Map outputs=0
GC time elapsed (ms)=0
Total committed heap usage (bytes)=371720192
File Input Format Counters
Bytes Read=18244

**Comment by Riaz123** [comment]
Hi Pranab,
Sorry for delayed response.
I followed  avenir/resource/price_optimize_tutorial.txt to create  properties file (prop.properties, placed in location : /home/avenir/resource/prop.properties) consists of following:


field.delim.regex=,
field.delim=,
num.reducer=1

#common MAB configurations
current.round.num=1
count.ordinal=3
reward.ordinal=6
global.batch.size=1
min.reward=0

#GreedyRandomBandit 
#There are other parameters which dafault to some vale. If you want to override. default, explicitly add them.
random.selection.prob=0.3
prob.reduction.algorithm=linear
prob.reduction.constant=2.0

#AuerDeterministic
det.algorithm=AuerUBC1

#RunningAggregator
rug.quantity.attr.ordinals=2
rug.id.field.ordinals=0,1
incremental.file.prefix=inc

**Comment by Riaz123** [comment]
Hi ,
I also want to add the below note:
I debugged org.avenir.reinforce.AuerDeterministic for the NullPointer exception error and found that in the dependent project chombo (org.chombo.util.Utility.java), lines 73, 74, 75 : 
public class Utility {
	private static final String CONF_FILE_PROP_NAME = "conf.path";
	private static final String FS_DEF_CONFIG_DIR = "/var/mawazo/";
	private static final String HDFS_DEF_CONFIG_DIR = "/var/mawazo/";
the CONF_FILE_PROP_NAME , FS_DEF_CONFIG_DIR and HDFS_DEF_CONFIG_DIR  are hard coded with the   file paths. Should I try changing these to my file path and build the project first & then create Uber jar ?
Please suggest.

**Comment by pranab** [comment]
The tutorial is out of sync with code changes. I will let you know when I update the tutorial

Sent from my iPhone

Pranab
http://www.linkedin.com/in/pkghosh
http://pkghosh.wordpress.com


On Dec 5, 2017, at 11:11 AM, Riaz123 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi ,
I also want to add the below note:
I debugged org.avenir.reinforce.AuerDeterministic for the NullPointer exception error and found that in the dependent project chombo (org.chombo.util.Utility.java), lines 73, 74, 75 :
public class Utility {
private static final String CONF_FILE_PROP_NAME = "conf.path";
private static final String FS_DEF_CONFIG_DIR = "/var/mawazo/";
private static final String HDFS_DEF_CONFIG_DIR = "/var/mawazo/";
the CONF_FILE_PROP_NAME , FS_DEF_CONFIG_DIR and HDFS_DEF_CONFIG_DIR are hard coded with the file paths. Should I try changing these to my file path and build the project first & then create Uber jar ?
Please suggest.

**Comment by Riaz123** [comment]
Thanks Pranab, Will wait for updated tutorial . Appreciate your effort.
In the mean while, any quick suggestion just to make org.avenir.reinforce.AuerDeterministic run? would be of great help.

I was thinking of trying spark implementation for Multi-Arm Bandit (org.avenir.spark.reinforce), would that be a good alternative? I see that you have UCB-2, Geedy epsilon , SOFT_MAX , SAMPSON_SAMPLER , EXPONENTIAL_WEIGHT implemented. These are the algorithms that I want to use to solve price optimization.
CAN YOU PLEASE TELL ME HOW TO CREATE RUNNABLE JAR WITH sbt, i see that "assemblyMergeStrategy" is missing in the build.sbt inside spark folder.

**Comment by pranab** [comment]
I found the issue. As per tutorial, you are supposed to copy agr_ret.txt only to HDFS input path in the step called "First round".  You are copying 3 files. Your input path needs to be HDFS. You seem to be using normal file system path.
I think the tutorial id OK, after all

**Comment by Riaz123** [comment]
Thanks Pranab! I'm able to run greedy epsilon and UCB for the 1st round with "current.round.num=1" in properties file.
I'm yet to try the more next round...
